apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - persistentVolumeClaim.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - ingress-tailscale.yaml
