apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: media
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: jellyfin
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8096
      targetPort: http
  selector:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: jellyfin
