apiVersion: v1
kind: Service
metadata:
  name: homeassistant-proxy
  namespace: default
spec:
  ports:
    - port: 80
      name: http
      targetPort: http
      protocol: TCP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: homeassistant-proxy
  namespace: default
  labels:
    kubernetes.io/service-name: homeassistant-proxy
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 8123
endpoints:
  - addresses:
      - "192.168.2.7"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant-proxy
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: ha.hoyes.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homeassistant-proxy
                port:
                  name: http
  tls:
    - hosts:
        - ha.hoyes.dev
      secretName: hoyes-dev-tls
