apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-services
  namespace: default
spec:
  interval: 10m
  releaseName: external-service-proxy
  chart:
    spec:
      chart: ./charts/external-service-proxy
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    services:
      octopi:
        ip: 192.168.2.6
        port: 80
        domain: octopi.hoyes.dev
        ingressAnnotations:
          nginx.ingress.kubernetes.io/proxy-body-size: 500m
      homeassistant:
        ip: 192.168.2.7
        port: 8123
        domain: ha.hoyes.dev
      launcher:
        ip: 192.168.2.20
        port: 2080
        domain: launch.hoyes.dev

    ingress:
      className: nginx
      tls:
        secretName: hoyes-dev-tls
