apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hoyes-dev-tls
  namespace: paperless
spec:
  secretName: hoyes-dev-tls
  dnsNames:
    - "hoyes.dev"
    - "*.hoyes.dev"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
