apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: paperless
  namespace: flux-system
spec:
  interval: 10m
  path: ./flux/apps/hoyeslab/paperless
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure-configs
    - name: dragonflydb
    - name: cloudnative-pg
