# Requires keys:
#   - secret_key
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: paperless-ngx
  namespace: paperless
spec:
  itemPath: "vaults/Infrastructure/items/paperless-ngx"
