apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  releaseName: ingress-nginx
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.12.2
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      service:
        type: LoadBalancer
        externalTrafficPolicy: Local

        # Create a separate ClusterIP service. This is typically used for a private
        # network load balancer, but we actually use it for Cloudflare Tunnels to
        # reach the ingress controller. So confusingly, this service is actually used
        # for public external traffic where as the default "external" service is used
        # for my private network.
        internal:
          enabled: true
          type: ClusterIP
          externalTrafficPolicy: Local
          annotations:
            # The chart requires annotations in order to create an internal service.
            dummy: "true"

      ingressClass: nginx
      ingressClassResource:
        name: nginx
        default: true
