apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  releaseName: ingress-nginx
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.13.2
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      service:
        externalTrafficPolicy: Local
      ingressClass: nginx
      ingressClassResource:
        name: nginx
        default: true

---

# ingress-nginx deployment that's meant to be paired with a Cloudflare Tunnel.
# This gets a ClusterIP service (not routable outside of the cluster) that a
# Cloudflare Tunnel can connect to.
# Use `ingressClassName: nginx-cloudflare` to route traffic to this ingress.
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx-cloudflare
  namespace: ingress-nginx
spec:
  releaseName: ingress-nginx-cloudflare
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.13.2
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      service:
        # The service doesn't need to be routable outside of the cluster.
        # We could also use controller.service.internal, but that's meant for
        # cloud environments where extra annotations are required for internal
        # load balancers, so there's no value in us using it here.
        type: ClusterIP
      ingressClass: nginx-cloudflare
      ingressClassResource:
        name: nginx-cloudflare
        controllerValue: "k8s.io/ingress-nginx-cloudflare"
        default: false
