apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx-tailscale
  namespace: ingress-nginx
spec:
  releaseName: ingress-nginx-tailscale
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.13.3
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      service:
        type: LoadBalancer
        loadBalancerClass: tailscale
        annotations:
          tailscale.com/hostname: ingress-nginx-tailscale
          external-dns.alpha.kubernetes.io/hostname: ingress-nginx-tailscale.hoyes.dev,*.ts.hoyes.dev
      ingressClass: nginx-tailscale
      ingressClassResource:
        name: nginx-tailscale
        controllerValue: "k8s.io/ingress-nginx-tailscale"
        default: false
