apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media
  labels:
    app.kubernetes.io/name: radarr
    app.kubernetes.io/instance: radarr
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: radarr
      app.kubernetes.io/instance: radarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: radarr
        app.kubernetes.io/instance: radarr
    spec:
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:6.1.1
          ports:
            - name: http
              containerPort: 7878
              protocol: TCP
          env:
            - name: PUID
              value: "1029"  # service-access user on Graham-DS920 NFS server
            - name: PGID
              value: "100"   # users group on Graham-DS920 NFS server
            - name: TZ
              value: "America/Toronto"
            - name: DOCKER_MODS
              value: "ghcr.io/themepark-dev/theme.park:radarr"
            - name: TP_THEME
              value: "nord"
          volumeMounts:
            - mountPath: /config
              name: radarr-config
            - mountPath: /data
              name: media
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          livenessProbe:
            initialDelaySeconds: 10
            tcpSocket:
              port: http
          readinessProbe:
            initialDelaySeconds: 10
            tcpSocket:
              port: http

      volumes:
        - name: radarr-config
          persistentVolumeClaim:
            claimName: radarr-config
        # Mount the entire media share so radarr can hard link
        # from /data/torrents/ to /data/media/movies/
        - name: media
          nfs:
            server: ds920.hoyes.dev
            path: /volume1/media
