apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  interval: 10m
  chart:
    spec:
      chart: longhorn
      version: 1.10.0
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    defaultSettings:
      # Mount point within the node where Longhorn stores data. This is created
      # by the ansible playbooks.
      # If not running in a VM with a dedicated mount, use a Kustomize patch to set this
      # back to /var/lib/longhorn/
      defaultDataPath: "/mnt/longhorn-storage/"
    defaultBackupStore:
      # Note: Longhorn, for whatever reason, makes connections from unprivileged ports (unlike
      # regular kubernetes NFS volumes). On the NFS Permissions for the share on Synology,
      # need to enable "Allow connections from non-privileged ports".
      backupTarget: "nfs://ds920.hoyes.dev:/volume1/backups/longhorn"
    ingress:
      enabled: true
      tls: true
      host: longhorn.hoyes.dev
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      tlsSecret: longhorn-tls
      ingressClassName: nginx
