apiVersion: v1
kind: Service
metadata:
  name: pihole  # Will be replaced in overlays
  namespace: default
  labels:
    app.kubernetes.io/name: pihole
    app.kubernetes.io/instance: pihole
    app.kubernetes.io/component: primary  # Will be replaced in overlays
spec:
  type: LoadBalancer
  ports:
    - port: 53
      targetPort: dns-udp
      protocol: UDP
      name: dns-udp
    - port: 53
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: pihole
    app.kubernetes.io/instance: pihole
    app.kubernetes.io/component: primary  # Will be replaced in overlays
