apiVersion: v1
kind: Service
metadata:
  name: pihole-tcp  # Will be replaced in overlays
  namespace: pihole
  labels:
    app.kubernetes.io/name: pihole
    app.kubernetes.io/instance: pihole
    app.kubernetes.io/component: primary  # Will be replaced in overlays
  annotations:
    metallb.universe.tf/allow-shared-ip: "pihole-primary"  # Will be replaced in overlays
    metallb.universe.tf/loadBalancerIPs: "192.168.20.61"  # Will be replaced in overlays
spec:
  type: LoadBalancer
  ports:
    - port: 53
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
  selector:
    app.kubernetes.io/name: pihole
    app.kubernetes.io/instance: pihole
    app.kubernetes.io/component: primary  # Will be replaced in overlays
