# The headless service is used to expose the Pi-hole API on each
# individual pod in the StatefulSet for nebula-sync. It doesn't need
# to expose DNS ports.
apiVersion: v1
kind: Service
metadata:
  name: pihole-headless  # Will be replaced in overlays
  namespace: pihole
  labels:
    app.kubernetes.io/name: pihole
    app.kubernetes.io/instance: pihole
    app.kubernetes.io/component: primary  # Will be replaced in overlays
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: pihole
    app.kubernetes.io/instance: pihole
    app.kubernetes.io/component: primary  # Will be replaced in overlays
