apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: paperless-dragonfly
  namespace: paperless
spec:
  replicas: 1
  env:
    - name: MAX_MEMORY
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
          divisor: 1Mi

  args:
    # Each IO thread requires 256 MiB of memory, so we are limited to 2 threads
    - --maxmemory=$(MAX_MEMORY)Mi
    - --proactor_threads=2

  resources:
    requests:
      cpu: 100m
    limits:
      memory: 512Mi
