{{- range $name, $service := .Values.services }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "external-service-proxy.fullname" $ }}-{{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "external-service-proxy.labels" $ | nindent 4 }}
  {{- if ( or $service.ingressAnnotations $.Values.ingress.annotations ) }}
  annotations:
    {{- with $.Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with $service.ingressAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  {{- with $.Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  tls:
    - hosts:
        - {{ $service.domain | quote }}
      secretName: {{ $service.tlsSecret | default $.Values.ingress.tls.secretName }}
  rules:
    - host: {{ $service.domain | quote }}
      http:
        paths:
          - path: {{ ( $service.path | default "/" ) | quote }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "external-service-proxy.fullname" $ }}-{{ $name }}
                port:
                  name: http
{{- end }}
