apiVersion: apps/v1
kind: Deployment
metadata:
  name: nebula-sync
  namespace: pihole
  labels:
    app.kubernetes.io/name: nebula-sync
    app.kubernetes.io/instance: nebula-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nebula-sync
      app.kubernetes.io/instance: nebula-sync
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nebula-sync
        app.kubernetes.io/instance: nebula-sync
    spec:
      containers:
        - name: nebula-sync
          image: ghcr.io/lovelaze/nebula-sync:v0.11.0
          env:
            - name: TZ
              value: "America/Toronto"
            - name: PRIMARY
              # Format is `http://pihole-primary-0.pihole-headless-primary|<password>`
              valueFrom:
                secretKeyRef:
                  name: pihole-admin
                  key: primary
            - name: REPLICAS
              # Format is `http://pihole-replica-0.pihole-headless-replica|<password>,http://pihole-replica-1.pihole-headless-replica|<password>`
              valueFrom:
                secretKeyRef:
                  name: pihole-admin
                  key: replicas
            - name: FULL_SYNC
              value: "false"
            - name: RUN_GRAVITY
              value: "false"
            - name: CRON
              value: "*/15 * * * *"

            # Replicas inside the cluster are over HTTP, but external replicas should be over HTTPS
            - name: CLIENT_SKIP_TLS_VERIFICATION
              value: "true"

            # Only using DNS
            - name: SYNC_CONFIG_DNS
              value: "true"
            - name: SYNC_CONFIG_DHCP
              value: "false"
            - name: SYNC_CONFIG_NTP
              value: "false"
            - name: SYNC_CONFIG_RESOLVER
              value: "false"
            - name: SYNC_CONFIG_DATABASE
              value: "true"
            - name: SYNC_CONFIG_MISC
              value: "true"
            - name: SYNC_CONFIG_DEBUG
              value: "false"

            - name: SYNC_GRAVITY_GROUP
              value: "true"
            - name: SYNC_GRAVITY_AD_LIST
              value: "true"
            - name: SYNC_GRAVITY_AD_LIST_BY_GROUP
              value: "true"
            - name: SYNC_GRAVITY_DOMAIN_LIST
              value: "true"
            - name: SYNC_GRAVITY_DOMAIN_LIST_BY_GROUP
              value: "true"
            - name: SYNC_GRAVITY_CLIENT
              value: "true"
            - name: SYNC_GRAVITY_CLIENT_BY_GROUP
              value: "true"
            - name: SYNC_GRAVITY_DHCP_LEASES
              value: "false"
