apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

nameSuffix: -replica

patches:
  - path: statefulset.patch.yaml
  - path: service-headless.patch.yaml
  - path: service-loadbalancer.patch.yaml
