apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pihole
  labels:
    app.kubernetes.io/component: replica
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: replica
  template:
    metadata:
      labels:
        app.kubernetes.io/component: replica
