apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: daily-snapshot
  namespace: longhorn-system
spec:
  cron: "0 0 * * *"  # Daily at midnight
  task: "snapshot"
  groups:
  - default
  retain: 21
  concurrency: 2
