apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: connect
  namespace: 1password
spec:
  releaseName: connect
  interval: 10m
  chart:
    spec:
      chart: connect
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: 1password
        namespace: flux-system
  values:
    connect:
      create: true
    operator:
      create: true
      authMethod: "connect"
