# Requires keys:
#   - endpoint_ip
#   - endpoint_port
#   - public_key
#   - private_key
#   - address
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: gluetun-qbittorrent
  namespace: media
spec:
  itemPath: "vaults/Infrastructure/items/qbittorrent gluetun wireguard"
