apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  releaseName: tailscale-operator
  interval: 10m
  chart:
    spec:
      chart: tailscale-operator
      version: 1.80.3
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
  values:
