apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  releaseName: tailscale-operator
  interval: 10m
  chart:
    spec:
      chart: tailscale-operator
      version: 1.84.2
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
  values:
    operatorConfig:
      hostname: ${CLUSTER_NAME}-operator
      image:
        repository: ghcr.io/tailscale/k8s-operator
    proxyConfig:
      image:
        repository: ghcr.io/tailscale/tailscale
