# Requires keys (chart's gitea.admin.existingSecret format):
#   - username
#   - password
#   - email
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: forgejo-admin
  namespace: forgejo
spec:
  itemPath: "vaults/Infrastructure/items/forgejo admin"
