apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml

nameSuffix: -primary

patches:
  - path: statefulset.patch.yaml
  - path: service-headless.patch.yaml
  - path: service-lb.patch.yaml
    target:
      kind: Service
      name: pihole-(tcp|udp)
