apiVersion: v1
kind: Service
metadata:
  name: not-important  # Uses target in kustomization.yaml
  namespace: pihole
  labels:
    app.kubernetes.io/component: primary
  annotations:
    metallb.io/allow-shared-ip: "pihole-primary"
    metallb.io/loadBalancerIPs: "192.168.20.61"
spec:
  selector:
    app.kubernetes.io/component: primary
