# This secret contains the Pi-hole admin password.
# It needs to have 3 fields:
# - password: The password for the Pi-hole admin interface
# - primary: The <primary host>|<password>
# - replicas: <replica 1 host>|<password>,<replica 2 host>|<password>,...
#
# The primary and replicas fields are to provide to the nebula-sync
# deployment. If we were using External Secrets Operator, this could be templated
# from just the password field.
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: pihole-admin
  namespace: pihole
spec:
  itemPath: "vaults/infrastructure/items/Pi-hole Admin"
