apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cloudflare-api-token
  namespace: external-dns
spec:
  # Secret must have a property named `cloudflare_api_token`
  itemPath: "vaults/Infrastructure/items/external-dns Cloudflare Token"
