apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  releaseName: external-dns
  interval: 10m
  chart:
    spec:
      chart: external-dns
      version: 1.19.0
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  values:
    policy: sync
    sources:
      - ingress
    txtOwnerId: ${CLUSTER_NAME}

    provider:
      name: cloudflare

    extraArgs:
      # Non-proxied internal records are captured by a wildcard DNS entry pointing
      # to the `nginx` ingress controller
      - --cloudflare-proxied
      - --cloudflare-dns-records-per-page=1000
      # Can specify this argument multiple times to monitor multiple ingress classes
      - --ingress-class=nginx-cloudflare

    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-token
            key: cloudflare_api_token
