- name: Update package cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install required packages
  ansible.builtin.apt:
    name:
      - qemu-guest-agent
      - open-iscsi
      - nfs-common
      - bridge-utils
      - nvme-cli
      - "linux-modules-extra-{{ ansible_kernel }}"

- name: Load required kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - br_netfilter
    - overlay
    - iscsi_tcp
    - vfio_pci
    - i915

- name: Persist kernel modules
  copy:
    dest: /etc/modules-load.d/k3s.conf
    content: |
      br_netfilter
      overlay
      iscsi_tcp
      vfio_pci
      i915

- name: Configure huge pages for Longhorn
  sysctl:
    name: vm.nr_hugepages
    value: '1024'
    state: present
    sysctl_file: /etc/sysctl.d/longhorn.conf

- name: Start iscsid service
  ansible.builtin.systemd:
    name: iscsid
    state: started
    enabled: yes

# See https://longhorn.io/kb/troubleshooting-volume-with-multipath/
- name: Stop and disable multipathd service
  ansible.builtin.systemd:
    name: multipathd
    state: stopped
    enabled: no

- name: Add multipathd blacklist configuration
  ansible.builtin.blockinfile:
    path: /etc/multipath.conf
    block: |
      blacklist {
          devnode "^sd[a-z0-9]+"
      }

# Disable systemd-resolved DNS stub listener
- name: Create systemd-resolved.conf.d directory
  file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    mode: '0755'

- name: Create resolved configuration file
  copy:
    dest: /etc/systemd/resolved.conf.d/disable-stub-listener.conf
    content: |
      [Resolve]
      DNSStubListener=no
    mode: '0644'
  notify: restart systemd-resolved
