apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: RELNAME
  namespace: NAMESPACE
spec:
  releaseName: RELNAME
  interval: 10m
  chart:
    spec:
      chart: RELNAME
      version: x.y.z
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: REPONAME
        namespace: flux-system
  values: {}
