k3s_version: v1.32.1+k3s1

# The user that gets SSH access into the VMs
ansible_user: root

# Cluster name, only used for display purposes
cluster_name: "HoyesLab"

# Timezone
system_timezone: "America/Toronto"
