ansible_user: root
network_bridge: vmbr0
proxmox_api_user: "root@pam"
proxmox_api_token_id: "ansible-automation"
proxmox_api_token_secret: "{{ vault_proxmox_api_token_secret }}"
vm_default_password: "{{ vault_vm_default_password }}"
cluster_name: "HoyesLab"