- name: Configure storage disks
  hosts: k3s_agents
  gather_facts: true
  tasks:
    - name: Format Longhorn disk with XFS
      community.general.filesystem:
        fstype: xfs
        dev: /dev/vdb

    - name: Configure Longhorn mount
      ansible.posix.mount:
        path: /mnt/longhorn-storage
        src: /dev/vdb
        fstype: xfs
        opts: defaults
        state: mounted


# Variables must be loaded now rather than as part of group_vars since they depend
# on the results of the previous tasks (VM creation in particular)
- name: Include k3s variables
  hosts: k3s_cluster
  gather_facts: true
  tasks:
    - include_vars: vars/k3s.yaml

- name: Prepare k3s nodes
  hosts: k3s_cluster
  gather_facts: true
  roles:
    - role: system_requirements
      become: true
    - role: techno_tim.k3s_ansible.prereq
      become: true
    # Download k3s binary
    - role: techno_tim.k3s_ansible.download
      become: true

- name: Setup k3s servers
  hosts: k3s_servers
  roles:
    - role: techno_tim.k3s_ansible.k3s_server
      become: true

- name: Setup k3s agents
  hosts: k3s_agents
  roles:
    - role: techno_tim.k3s_ansible.k3s_agent
      become: true

- name: Configure k3s cluster
  hosts: k3s_servers
  roles:
    - role: techno_tim.k3s_ansible.k3s_server_post
      become: true

- name: Reboot k3s cluster nodes
  hosts: k3s_cluster
  gather_facts: false
  tasks:
    - name: Rebooting {{ inventory_hostname }}
      ansible.builtin.reboot:
        reboot_timeout: 600
        msg: "Reboot initiated by Ansible for k3s cluster"

- name: Storing kubeconfig in the playbook directory
  hosts: k3s_servers[0]
  tasks:
    - name: Copying kubeconfig from {{ inventory_hostname }}
      ansible.builtin.fetch:
        src: "{{ ansible_user_dir }}/.kube/config"
        dest: "./kubeconfig"
        flat: true
