- name: Download Ubuntu cloud image
  hosts: proxmox[0]
  gather_facts: true
  tasks:
    # This assumes that `proxmox_image_storage` is a shared drive (NFS, CephFS, etc) that all
    # nodes can access. If using a local drive, move these tasks down to the next section
    # that runs on all nodes.
    - name: Create images directory
      file:
        path: /mnt/pve/{{ proxmox_image_storage }}/template/iso/
        state: directory
        mode: '0755'
    
    - name: Download Ubuntu cloud image
      get_url:
        url: "{{ cloud_image_url }}"
        dest: /mnt/pve/{{ proxmox_image_storage }}/template/iso/{{ cloud_image_name }}
        force: no  # Don't redownload if exists

- name: Create VMs from Ubuntu cloud image
  hosts: proxmox
  gather_facts: true
  tasks:
    - name: Set fact for VMs on this host
      set_fact:
        vms_to_create: >
          {{
            groups['k3s_cluster']
            | map('extract', hostvars)
            | selectattr('proxmox_host', 'eq', inventory_hostname)
            | list
          }}

    - name: Create VM
      loop: "{{ vms_to_create }}"
      loop_control:
        loop_var: vm_config
        label: "Creating {{ vm_config.inventory_hostname }}"
      include_tasks: tasks/create-vm.yaml
    
- name: Configure base system requirements
  hosts: k3s_cluster
  become: true
  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - qemu-guest-agent
          - open-iscsi
          - nfs-common
          - bridge-utils
          - nvme-cli

    - name: Load required kernel modules
      modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - br_netfilter
        - overlay
        - iscsi_tcp
        - vfio_pci
        # - uio_pci_generic
        - nvme-tcp

    - name: Persist kernel modules
      copy:
        dest: /etc/modules-load.d/k3s.conf
        content: |
          br_netfilter
          overlay
          iscsi_tcp
          vfio_pci
          nvme-tcp
    
    - name: Configure huge pages for Longhorn
      sysctl:
        name: vm.nr_hugepages
        value: '1024'
        state: present
        sysctl_file: /etc/sysctl.d/longhorn.conf

    - name: Configure kernel peramaters for K3s
      sysctl:
        name: "{{ item }}"
        value: "1"
        state: present
        sysctl_file: /etc/sysctl.d/k3s.conf
      loop:
        - net.bridge.bridge-nf-call-iptables
        - net.bridge.bridge-nf-call-ip6tables
        - net.ipv4.ip_forward
      
