apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cloudflare-tunnel-credentials
  namespace: cloudflare
spec:
  # Secret must have a file named `credentials.json`
  itemPath: "vaults/infrastructure/items/${CLUSTER_NAME} Cloudflare Tunnel"
