apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: node-feature-discovery
spec:
  releaseName: node-feature-discovery
  interval: 10m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.17.3
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
        namespace: flux-system
  values: {}
